# Generated by Django 2.1.1 on 2018-09-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContracorServices',
            new_name='ContractorServices',
        ),
    ]
