# Generated by Django 2.1.1 on 2018-09-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180928_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorServices',
            new_name='ContractorSpecialty',
        ),
    ]
