# Generated by Django 2.1.1 on 2018-09-29 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20180928_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('actual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.City'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 9, 29, 0, 23, 42, 716827)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contractor'),
        ),
    ]
