# Generated by Django 2.1.1 on 2018-09-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180929_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuse',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductUse',
        ),
    ]
