# Generated by Django 2.1.1 on 2018-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tagproduct_tagservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagproduct',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
    ]
